### ISSUE TITLE
svg improvements

### ISSUE THREAD

**Issue by TheJJ** [frickler01/openage-design#4]
- tile-text.svg looks nice but the A is flipped.
- crown.svg should have some outline at the white socket, alternatively don't leave the circle.
- antique-helmet.svg is awesome!
- helmet-logo.svg could be a nice startup image, but the A should be flipped as well
- the font of tile-letters.svg is cool, but again the flipped A would look better

I like the abstract art style, this will hopefully be going upstream soon, the svgs are no binaries so we can then let the buildsystem render some rasterized output from them if needed.

**Comment by fricklerhandwerk** [comment]
The age `A` is flipped because, as you can see from [sketches/png/52.png](https://github.com/frickler01/openage-design/blob/master/sketches/png/52.png) (3), otherwise it would dangerously look like `PGE`, unless you flip the other letters as well (2). This on the other hand is also only suboptimal I think, since the the cut down `G` could as well be interpreted as a stylized `O` - unless you like the ambiguity.

The white socket of crown.svg was an artifact; fixed.

**Comment by fricklerhandwerk** [comment]
Adding another inner edge to the `G` fixes the ambiguity.

Interestengly, if I fix the parallels and line thickness on the helmet logo (compare [helmet-logo.png](../blob/master/svg/helmet-logo.svg) and [helmet-logo2.png](../blob/master/svg/helmet-logo2.svg)), it looks worse. Not because it's more static, but because the negative space intrudes too much.
